version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mercadata-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dev_testeos
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mercadata:
    build: .
    container_name: mercadata-app
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: dev_testeos
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - .:/app
    command: python main.py

volumes:
  db_data:
