apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mercadata-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tu_usuario/tu_repo
    targetRevision: HEAD
    path: infra/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated: {}
